### ISSUE TITLE
[Support] WhatsApp Client Support

### ISSUE THREAD

**Issue by eazyAlf** [johnboiles/obs-mac-virtualcam#237] opened 2020-11-22 13:37 UTC
**Describe the issue**
There is a new feature within the WhatsApp Client on macOs that allows usage of webcam now.
I've tried with re-codesign the application and it worked, for a bit. Don't know if there has been an update or if it could be related to disabling SIP, but since today I can't use OBS Virtual Camera within WhatsApp anymore.

I've tried everything I could and the only thing i found out as a workaround is, that once I open the WhatsApp Helper (/Applications/WhatsApp.app/Contents/Frameworks/WhatsApp Helper.app) I am able to use it, but the resolution/renderer won't load properly.

**To Reproduce**
_Steps to reproduce the behavior:_
Set up the OBS Camera as your camera – with the call starting all I'll see is a black screen, once the call is answered, WhatsApp tells me my camera is not supported and I should contact the support (which wasn't helpful)

**Behavior**
Not sure what it was related to, but since I've had problems in Telegram I disabled SIP, since I've disabled SIP, Telegram is working fine.. but now neither WhatsApp nor Photoboot (which were working fine before, only by re-codesigning the main application, doing nothing with the helpers) I have this issue.

**Screenshots**
Camera is visible:
![image](https://user-images.githubusercontent.com/58122515/99905458-2118ea00-2cd1-11eb-9497-810a260eb8f4.png)
No Preview available:
![image](https://user-images.githubusercontent.com/58122515/99905472-368e1400-2cd1-11eb-8ed9-ab8cb9ad5764.png)
When Helper is started instead:
![image](https://user-images.githubusercontent.com/58122515/99905520-879e0800-2cd1-11eb-8548-fcaaf1acaa68.png)

**Desktop (please complete the following information):**
 - OS version: [e.g. macOS Catalina 10.15.6]
 - Application: WhatsApp Client / electron application
 - Virtualcam version: v1.2.1
 - OBS version: 26.0.2

**Additional context**

**Comment by gxalpha** [comment] 2020-11-22 13:48
Hi, could you please fill out the template?

**Comment by eazyAlf** [comment] 2020-11-22 13:50
@gxalpha – sorry.. just did. My first issue I am reporting.

**Comment by johnboiles** [comment] 2020-11-27 05:51
Most likely, WhatsApp has moved plugin loading to a separate process for security reasons (This is what Zoom and Chrome do). Try re-codesigning `WhatsApp Helper.app` and maybe looking around in the `WhatsApp.app` for other processes you might need to re-codesign.

**Comment by johnboiles** [comment] 2020-12-14 23:42
Duplicate of #4.

**Closed by johnboiles** 2020-12-14 23:42 UTC
