### ISSUE TITLE
[Bug] Ancient MBP with High Sierra Problems

### ISSUE THREAD

**Issue by jdgwf** [johnboiles/obs-mac-virtualcam#107] opened 2020-05-14 17:20 UTC
I know this is going to be fringe case, so I don't expect too much, but I was wanting to at least inform you of the results :)

**Describe the issue**
When using virtual cam of virtual cam in OBS the picture is all "wound up" I see movement of the camera, but it's not clear (see screenshots below)
Discord never gets past the "Start Virtual Camera" screen even with the Virtual Camera on

**To Reproduce**
It might just be this ancient MBP, but I'm an OBS vet (and this works BEAUTIFULLY on my ~2015 iMac!)

**Behavior**
See screenshots of distorted picture below

**Screenshots**

Discord Test Preview
![Screen Shot 2020-05-14 at 12 05 50 PM](https://user-images.githubusercontent.com/316824/81964991-073d7280-95dd-11ea-8de6-c25f53cb4e14.png)

In-OBS - bottom left is live webcam, and top right is a feedback of the OBS Virtual Camera
![Screen Shot 2020-05-14 at 12 05 39 PM](https://user-images.githubusercontent.com/316824/81964992-07d60900-95dd-11ea-8a20-fe76d061859f.png)

**Desktop (please complete the following information):**
 - OS version: macOS High Sierra 10.13.6
 - Latest OBS and Discord
 - Version [e.g. 1.0.0]

**Additional context**

**Comment by jdgwf** [comment] 2020-05-14 17:21
Again, this works BEAUTIFULLY on my ~2015 iMac (will try my 2009 MacPro later today or tomorrow), so treat this as more informative than a support request.

**Comment by jdgwf** [comment] 2020-05-14 17:39
Currently uninstalling OBS and the old virtcam driver just in case...
![Screen Shot 2020-05-14 at 12 36 02 PM](https://user-images.githubusercontent.com/316824/81967040-f6423080-95df-11ea-84ce-35bf43b47112.png)

Will reboot/reinstall and let you know the results

**Comment by jdgwf** [comment] 2020-05-14 17:57
Same problem even after uninstall, reboot, reinstall obs (to make sure Virtual Cam was not there), reinstall of Virtual Cam and identical distortion of image.

**Comment by jdgwf** [comment] 2020-05-14 20:50
As I suspected, the driver works great with an moderately upgraded 2009 MacPro on High Sierra 
![Screenshot 2020-05-14 15 48 46](https://user-images.githubusercontent.com/316824/81984587-a3c23d80-95fa-11ea-9f12-c3fd410990a0.png)
:)

**Comment by johnboiles** [comment] 2020-05-14 23:12
This is a weird one!

To me the OBS screenshot looks like a mismatch in the resolution of what's getting sent from the the plugin vs what OBS is expecting. But then no idea why that would affect video showing in discord.

**Comment by Tifaifai** [comment] 2020-05-15 15:10
Hi, in my case, identical probem but i resolve this by : output resolution 1920x1080 in OBS.
Mac 10.14, OBS 25.0, OBS VirtualCam 1.1, Zoom 4.6.8 OK
In discord 0.0.257, no camera detect

**Comment by Jhonsebas77** [comment] 2020-05-16 19:50
![Captura de Pantalla 2020-05-16 a la(s) 2 46 26 p  m](https://user-images.githubusercontent.com/19936907/82128882-39d59f80-9784-11ea-92fa-7d1e30501ebd.png)
Same issue

**Comment by johnboiles** [comment] 2020-05-28 23:05
@jdgwf @Jhonsebas77 @Tifaifai I think this should be fixed in the latest [release](https://github.com/johnboiles/obs-mac-virtualcam/releases/tag/v1.2.0). Could yall give it a try and report back?

**Comment by jdgwf** [comment] 2020-05-28 23:18
I just installed - the Virtual Camera service now gives me the 'Tools'->'Start Camera' blue screen whether the service is running or not. Installed and even rebooted just in case an older version of it was still in memory.
It's a mute point for me, I'm retiring that old MBP anyway :)

**Comment by johnboiles** [comment] 2020-05-28 23:36
You don't get the distortion in OBS anymore right?

**Comment by johnboiles** [comment] 2020-05-29 17:49
Any sort of Console.app logs when you open Discord on macOS 10.13 and try to use the virtual camera would be helpful. Sounds like the inter-process communication to OBS is breaking down for some reason.

**Comment by Jhonsebas77** [comment] 2020-05-30 20:25
> @jdgwf @Jhonsebas77 @Tifaifai I think this should be fixed in the latest [release](https://github.com/johnboiles/obs-mac-virtualcam/releases/tag/v1.2.0). Could yall give it a try and report back?

For me, it works great!

**Comment by johnboiles** [comment] 2020-12-14 23:21
This is more or less a duplicate of #160 I think. Closing (but maybe I'll leave that open after I archive this repo, for reference)

**Closed by johnboiles** 2020-12-14 23:21 UTC
Labels: bug
