### ISSUE TITLE
Unable to find “Browser” source

### ISSUE THREAD

**Issue by budisangithub** [johnboiles/obs-mac-virtualcam#36] opened 2020-04-22 04:06 UTC
Following the guidance to build obs and the virtual camera plugin, and Manage to have it up and running 

Work well with Webex Meeting, and able to have Webex Meeting to take video from OBS Virtual Camera

The issue may not related to virtual camera plugin, but I can’t find “Browser” source in the OBS

Secondly, understand that Resolution is hardcoded to 1280x720, any guidance how to change this manually ?

**Comment by hkatzdev** [comment] 2020-04-22 04:34
Browser source is possible when built with the OBS CI scripts, so it is not a virtualcam problem. If you want to try it out I built a package you can download at https://github.com/johnboiles/obs-mac-virtualcam/issues/23#issuecomment-616042871. OBS recently changed their CI system though and I haven't gotten around to figuring out how that one works. Also I believe this is a duplicate of #27.

As for the resolution, I don't know how to change that, sorry.

**Comment by gxalpha** [comment] 2020-04-22 08:05
> Secondly, understand that Resolution is hardcoded to 1280x720, any guidance how to change this manually ?

Check out PR #11, you can use my fork instead of johns. 

> Also I believe this is a duplicate of #27.

It is. Could be added to known issues tho @johnboiles

**Comment by johnboiles** [comment] 2020-04-23 20:19
Going to close this one since (as @signalwerk mentions) this is not a virtualcam problem.

Thanks to @cienijr's work in #42 we are very close to having the infrastructure to automatically build a version of this plugin that should run with prod OBS 25.0.7. So hopefully this class of  your-build-instructions-dont-include-plugin-X type issues will go away soon since people will just be able to use the build provided from [obsproject.com](https://obsproject.com/). The last step there is figure out the best practice for codesigning plugins. I'm chatting about it in [Discord](https://discordapp.com/channels/348973006581923840/374637102551400468/702974753245364274) and also asked @cienijr [what they recommend](https://github.com/johnboiles/obs-mac-virtualcam/pull/42#issuecomment-618629810).

**Closed by johnboiles** 2020-04-23 20:20 UTC
