### ISSUE TITLE
Failed to load 'en-US' text for module:

### ISSUE THREAD

**Issue by dataopt** [johnboiles/obs-mac-virtualcam#31] opened 2020-04-17 18:02 UTC
I followed the installation instructions. When I ran obs, I got a window saying "Failed to find locale/en-US.ini". The following appeared in the terminal:
````
warning: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
info: Decklink API Compiled version 10.11.4
info: Decklink API Installed version 11.5
info: [VideoToolbox encoder]: Adding VideoToolbox H264 encoders
warning: Failed to load 'en-US' text for module: 'obs-mac-virtualcam.so'
error: os_dlopen(/Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so->/Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so): dlopen(/Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so, 257): Library not loaded: @executable_path/../Frameworks/QtWidgets.framework/Versions/5/QtWidgets
  Referenced from: /Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so
  Reason: image not found

warning: Module '/Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so' not loaded
````

Any help is greatly appreciated.

**Comment by gxalpha** [comment] 2020-04-17 18:05
The locales thing, isn't the problem, it's just a warning. Your error is caused by something with QT. Has the QT5-Installation successfully completed? Try installing it again with `brew install Qt5` and check for errors.

**Comment by dataopt** [comment] 2020-04-17 18:09
I will try that.  Thanks.  But after clicking Start Virtual Camera, I don't  see the virtual camera in Photo Booth or QuickTime Player or OBS.  The loaded modules do include obs-mac-virtualcam.so.

How should I be testing if things are working?

**Comment by gxalpha** [comment] 2020-04-17 18:17
You need to start the virtual camera first and then start the App you want to use it in. It wont work if the App is already open.

**Comment by dataopt** [comment] 2020-04-17 18:18
That's what I did: I opened OBS, Start Virtual Camera, and open QuickTime Player and New Movie Recording. It said I have no camera.

**Comment by johnboiles** [comment] 2020-04-17 22:01
Are you sure QuickTime was fully closed before you opened it?

**Comment by dataopt** [comment] 2020-04-18 09:31
I rebooted and tried the whole process again. Nothing.

With the command
````
ioreg -p IOUSB -w0 | sed 's/[^o]*o //; s/@.*$//' | grep -v '^Root.*'
````
I got the list:
````
AppleUSBEHCI Root Hub Simulation
IOUSBHostDevice
BRCM20702 Hub
Bluetooth USB Host Controller
AppleUSBXHCI Root Hub Simulation
Keyboard Hub
Apple Keyboard
````
It doesn't look like any of these is a camera. What else should I try?

**Comment by dataopt** [comment] 2020-04-18 10:17
I tried the installation from scratch again. It's working now! Thanks.

I must have missed some step somewhere.

**Comment by hkatzdev** [comment] 2020-04-19 06:00
I am also getting `Failed to load 'en-US' text for module: 'obs-mac-virtualcam.so'`. However, I haven't noticed any sides effects of this.

**Comment by gxalpha** [comment] 2020-04-19 09:50
Yes, as I said, it is expected that you don't find this.

**Comment by johnboiles** [comment] 2020-04-22 17:34
Closing since the local warning message is expected for now.

**Closed by johnboiles** 2020-04-22 17:34 UTC
