### ISSUE TITLE
[BUG] Skype v8.60.0.76 / Discord OBS Virtual Camera no longer available/working

### ISSUE THREAD

**Issue by stickpin** [johnboiles/obs-mac-virtualcam#131] opened 2020-05-19 17:45 UTC
**Describe the bug**
Microsoft released a new Skype version today v8.60.0.76 and OBS Virtual Camera is no longer displayed in the selection list. I've tried to do a `codesign --remove-signature` trick but it's not working anyway.
Previous version: v8.59.0.77 working fine.

**Desktop (please complete the following information):**
 - OS version: macOS Catalina 10.15.4
 - Application: Skype v8.60.0.76
 - Virtualcam version: v1.1.0
 - OBS version: 25.0.8

**Comment by johnboiles** [comment] 2020-05-19 21:08
Interesting. I wonder if Skype followed Zoom and disabled 3rd party camera plugins.

**Comment by pwnell** [comment] 2020-05-19 21:10
I think so as I also do not see my BlackMagic UltraStudio 4k mini in skype or any of the other virtual cams (Wirecast / ecamm) which worked yesterday before I updated today a well.

**Comment by johnboiles** [comment] 2020-05-19 21:13
I'd also try re-codesigning zoom manually (probably need xcode installed for this) 

    sudo codesign -f -s - /Applications/zoom.us.app

And if that doesn't work maybe try the more elaborate fixes to change the entitlements that were shared by some folks in #4. Please report back if you do this as I don't think anyone came up with a reusable command for this.

**Comment by pwnell** [comment] 2020-05-19 21:15
Codesigning does nothing.  I did not test entitlements yet.

**Comment by johnboiles** [comment] 2020-05-19 21:17
Also keep an eye on Console.app while you open Skype and see if you see anything related to obs, CoreMedia, cameras, etc.

**Comment by pwnell** [comment] 2020-05-19 21:19
error	14:18:24.395447-0700	Skype Helper (Renderer)	Cannot find function pointer PlugInMain for factory <CFUUID 0x7f8f984a70b0> 35FDFF29-BFCF-4644-AB77-B759DE932ABE in CFBundle/CFPlugIn 0x7f8f984a7a50 </Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin> (bundle, not loaded)
error	14:18:24.395493-0700	Skype Helper (Renderer)	CMIO_DAL_PlugInManagement.cpp:913:CreatePlugIn CFPlugInInstanceCreate return NULL

**Comment by johnboiles** [comment] 2020-05-19 21:21
Ooh interesting. Can you run this and check the `obs-mac-virtualcam` version? `cat /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/Info.plist | grep -a3 CFBundleShortVersionString`

And check to see if there was log right before that in Console. Might not have come from the Skype process. Usually the log you posted happens when the plugin is blocked from loading for some reason (usually codesigning).

**Comment by pwnell** [comment] 2020-05-19 21:23
Downloaded it an hour ago so it should be the latest.

`	<string>OBS Virtual Camera</string>
	<key>CFBundlePackageType</key>
	<string>BNDL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.1.0</string>
	<key>CFBundleVersion</key>
	<string>1.1.0</string>`

**Comment by pwnell** [comment] 2020-05-19 21:25
All I see is:

`default	14:24:02.839396-0700	Skype Helper	Error loading /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam:  dlopen(/Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam, 262): no suitable image found.  Did find:
	/Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam: code signature in (/Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam) not valid for use in process using Library Validation: mapping process and mapped file (non-platform) have different Team IDs
	/Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam: stat() failed with errno=1
error	14:24:02.839458-0700	Skype Helper	Cannot find function pointer PlugInMain for factory <CFUUID 0x7fbf4fe0dc50> 35FDFF29-BFCF-4644-AB77-B759DE932ABE in CFBundle/CFPlugIn 0x7fbf4fe0fa70 </Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin> (bundle, not loaded)
error	14:24:02.839502-0700	Skype Helper	CMIO_DAL_PlugInManagement.cpp:913:CreatePlugIn CFPlugInInstanceCreate return NULL
error	14:24:02.841476-0700	Skype Helper	AddInstanceForFactory: No factory registered for id <CFUUID 0x7fbf4fe0d320> 30010C1C-93BF-11D8-8B5B-000A95AF9C6A
`

**Comment by pwnell** [comment] 2020-05-19 21:27
"have different Team IDs" there is the issue

**Comment by johnboiles** [comment] 2020-05-19 23:00
Yep, that's it. I think that's the same error we get with Zoom, but I don't remember off the top of my head. I'd try re-codesigning Skype and adding the [com.apple.security.cs.disable-library-validation](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_cs_disable-library-validation?language=objc) entitlement like people were doing for Zoom in #4. That's my best guess for a workaround.

**Comment by stickpin** [comment] 2020-05-20 10:31
> Yep, that's it. I think that's the same error we get with Zoom, but I don't remember off the top of my head. I'd try re-codesigning Skype and adding the [com.apple.security.cs.disable-library-validation](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_cs_disable-library-validation?language=objc) entitlement like people were doing for Zoom in #4. That's my best guess for a workaround.

I've tried the procedure with no luck. :(

Crashing with the following message:
```
Exception Type:        EXC_BAD_ACCESS (Code Signature Invalid)
Exception Codes:       0x0000000000000032, 0x000037d298442040
Exception Note:        EXC_CORPSE_NOTIFY
```

**Comment by johnboiles** [comment] 2020-05-20 15:32
@stickpin can you share the commands you ran to add the entitlement? I suspect something went wrong with codesigning after you changed the entitlement.

**Comment by stickpin** [comment] 2020-05-20 15:36
@johnboiles 
```
APPLICATION=/Applications/Skype.app && \
codesign -d --entitlements :- $APPLICATION | \
sudo codesign --sign <long_hex_dev_id> $APPLICATION --force --preserve-metadata=identifier,resource-rules,flags --entitlements=entitlements.xml
```
entitlements.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.security.cs.disable-library-validation</key>
	<true/>
</dict>
</plist>
```

**Comment by davelse** [comment] 2020-05-21 02:25
not sure if this is the right place to post but I downloaded a previous version (8.59.0.77) for the time being so that the virtual cam would work.  Also tried codesign as mentioned  already above (like I did with Zoom) and it did not work.  I also noticed that Skype also automatically updates the version the next time you start skype and will in turn remove the virtual cam.  So I had to create a script to disable the update.

/bin/launchctl setenv DISABLE_UPDATE_CHECK 1

Hopefully this will help those like me who is not so smart in coding to temporary use the previous version for now.  Hopefully someone can figure out how to overcome this bug.  Seems intentional that everyone is starting to disable virtual cam capabilities.

This command line needs to be run every time you restart your mac because the auto update will be enabled again after a restart.  So be sure to run this script first before opening Skype.

**Comment by johnboiles** [comment] 2020-05-21 04:43
Thanks for the tip @davelse.

Yeah the way Apple has architected virtual cameras isn't very secure unfortunately and a malicious virtual camera could access memory from host apps. That is why a lot of apps are disabling them. Apple could solve this by running virtual cameras in a separate process from the host program. That is how Chrome mitigated this issue, but it would make sense for something similar to happen at the OS level. Hopefully Apple will do something about it in 10.16!

**Comment by stickpin** [comment] 2020-05-21 18:57
FYI:

In case you have Little Snitch, you can block `get.skype.com` domain, which will also block Skype updates.
<img width="444" alt="Screenshot 2020-05-21 at 20 54 57" src="https://user-images.githubusercontent.com/630000/82595218-84e91b80-9ba5-11ea-8be5-fe3838368503.png">

**Comment by chrisspiegl** [comment] 2020-05-23 13:28
I have tried multiple ways of doing the `entitlements.txt` fix and Skype does start for me, but it does not load the virtual cameras. Not the OBS one neither any other. So it may be a different kind of problem here?

It's becoming quite annoying that these app providers are closing down like that.

**Comment by redsector72** [comment] 2020-05-28 23:19
Thanks for the great Thread.
For fixing Skype I had to dig a little.
It is necessary to "unsign" or resign an helper

here is the command
sudo codesign --remove-signature /Applications/Skype.app/Contents/Frameworks/Skype\ Helper\ \(Renderer\).app/

**Comment by johnboiles** [comment] 2020-05-28 23:57
Great trick, could you add those steps to the [Compatibility](https://github.com/johnboiles/obs-mac-virtualcam/wiki/Compatibility) section on the wiki?

**Comment by davelse** [comment] 2020-05-29 00:59
> Thanks for the great Thread.
> For fixing Skype I had to dig a little.
> It is necessary to "unsign" or resign an helper
> 
> here is the command
> sudo codesign --remove-signature /Applications/Skype.app/Contents/Frameworks/Skype\ Helper\ (Renderer).app/

Excellent!  Thank you!  
I tried copying and pasting the command and received an error saying "no matches found".  I realized there is a couple of dashes missing at the end.  In case anyone wants to copy and paste, this should work...  But thank you redsector72 for the command and johnboiles for this thread.

sudo codesign --remove-signature /Applications/Skype.app/Contents/Frameworks/Skype\ Helper\ \\(Renderer\\).app

**Comment by lennarto** [comment] 2020-06-06 18:01
Thanks all! For me, only this one worked: 1 backslash instead of 2 around (Renderer):

`sudo codesign --remove-signature /Applications/Skype.app/Contents/Frameworks/Skype\ Helper\ \(Renderer\).app`

**Comment by antman2** [comment] 2020-06-19 14:22
By way of the Ecamm help center, [Virtual Camera Missing After Skype Update](https://support.ecamm.com/en/articles/4063085-virtual-camera-missing-after-skype-update), a version of the command without backslashes (quotes instead):
```
codesign --remove-signature "/Applications/Skype.app/Contents/Frameworks/Skype Helper (Renderer).app"
```
Worked for me with Skype 8.61.0.95.

**Comment by miclaus** [comment] 2020-11-21 18:24
The `--remove-signature` worked for me as well.

Is there a way to readd the signature back?

**Comment by gxalpha** [comment] 2020-11-22 12:16
Well, then the virtual camera will likely not work anymore.
So yes, you could, but then you would have the problem you had before again.

**Comment by miclaus** [comment] 2020-11-22 19:37
@gxalpha yes, however it would be good to know how to readd/restore the signature, since removing the signature has implications, no?

**Comment by gxalpha** [comment] 2020-11-23 14:54
You would probably have to reinstall the app to get the original signature back

**Comment by johnboiles** [comment] 2020-12-14 23:26
Closing as a duplicate of #4. But it would probably be good to compile all these code signing workarounds for various apps into a page on the OBS wiki or something.

**Closed by johnboiles** 2020-12-14 23:26 UTC
Labels: compatibility
