### ISSUE TITLE
[BUG] Strange Camera Distortion on v1.2.0 of Virtualcam

### ISSUE THREAD

**Issue by arciniegx** [johnboiles/obs-mac-virtualcam#192] opened 2020-08-05 02:35 UTC
### **Strange Camera Distortion on v1.2.0 of Virtualcam**

Yelp _!_

### **Behavior**
The GIF below shows how the output of the content on the OBS Studio is distorted when streamed into Google Meets. I've been able to replicate with other platforms and "webcamtests.com" on Chrome.

### **To Reproduce**
Steps to reproduce the behavior is the same as the suggested steps to [install Virtualcam](github.com/johnboiles/obs-mac-virtualcam#installing). I was able to run Virtualcam without the distortion the first time I installed it, after restarting my Mac the effect appeared and persisted.

### **Assessments to Resolve Problem**
I've restarted my Mac a few times to resolve the problem to no avail. I've also [uninstalled](https://github.com/johnboiles/obs-mac-virtualcam#uninstalling) and reinstalled Virtualcam, OBS, and Chrome. This effect continues to be streamed on Meets, other participants on the conference see the distorted effect. 

### **Screenshots**
<img width="700" alt="Preview" src="https://user-images.githubusercontent.com/54507738/89362233-f3ad1f80-d692-11ea-8bdb-12a4f2ebb04a.png">
<img width="700" alt="Result" src="https://user-images.githubusercontent.com/54507738/89362853-7edae500-d694-11ea-8ef0-5e5ec6add619.png">

### **Recording of Behavior**
![Effect](https://user-images.githubusercontent.com/54507738/89362467-9a91bb80-d693-11ea-8025-92a9b6ffa00f.gif)

**Context**
 - macOS version: macOS Catalina 10.15.6
 - Application: Chrome, Opera (& GX)
 - Virtualcam version: 1.2.0
 - OBS version: 25.0.8

:(

**Comment by gxalpha** [comment] 2020-08-06 11:20
Hey @arciniegx ,

this is indeed a bug. Unfortunately, we don't know what exactly causes it and how to fix it. There are some janky workarounds in #160 where this is described better, but I'm not sure that I can really help you with that one :( (though it looks like the problem sometimes fixes itself).

As this looks like a duplicate of #160 I'm going to close it, but please keep track of #160 as results would probably be found and published there first.

**Closed** 2020-08-06 11:20 UTC
Labels: bug, duplicate
