### ISSUE TITLE
[BUG] Does not appear in Zoom 5.0.4

### ISSUE THREAD

**Issue by thompk2** [johnboiles/obs-mac-virtualcam#164] opened 2020-06-06 01:19 UTC
**Describe the bug**
According to the Zoom release notes, 5.0.4 re-enables support for virtual webcams. I can confirm other virtual cameras (like snap camera) now appear as options for zoom. However this virtual cam still does not appear in the list of webcams. I'm not sure why this would be exactly.

Here are the zoom release notes: https://support.zoom.us/hc/en-us/articles/360043996131-New-updates-for-May-24-2020

**To Reproduce**
1. Install Zoom 5.0.4 or later (I used 5.0.5)
2. Click on 'Start' in the meetings panel
3. Join (or don't!) audio by desired method
4. Click on 'Start Video' disclosure arrow
5. View list of hardware and virtual cameras

**Expected behavior**
OBS Virtual Camera appears in list of Zoom cameras

**Screenshots**
***Missing From Zoom***
<img width="448" alt="Screen Shot 2020-06-05 at 9 12 34 PM" src="https://user-images.githubusercontent.com/1895161/83932569-5bb5b700-a771-11ea-88fa-bcce925004ea.png">

***Working as expected in google hangouts***
<img width="363" alt="Screen Shot 2020-06-05 at 9 14 35 PM" src="https://user-images.githubusercontent.com/1895161/83932597-a5060680-a771-11ea-85a7-4deac19685e7.png">

**Desktop (please complete the following information):**
 - OS version: [macOS Catalina 10.15.4 (19E266)]
 - Application: [Zoom]
 - Virtualcam version: [v1.2.0]
 - OBS version: [25.0.8]

**Additional context**
This is a very new version of zoom, so I'm not entirely sure if it's on zoom here, or this plugin. But figured I should bring it up.

**Comment by dodgepong** [comment] 2020-06-06 02:03
Duplicate of #4

**Closed** 2020-06-06 07:45 UTC

**Comment by gxalpha** [comment] 2020-06-06 07:52
Also see the Compatibility file in the wiki for solutions! https://github.com/johnboiles/obs-mac-virtualcam/wiki
