### ISSUE TITLE
Feature request: create a way to start OBS with virtual camera on

### ISSUE THREAD

**Issue by lisaross** [johnboiles/obs-mac-virtualcam#53] opened 2020-04-27 20:53 UTC
Hey hey - I didn't see anything in the readme about feature request procedure so I'm hoping this isn't offensive. I just wanted to note this as a request for someday down the road. 

I thought a flag like -startstreaming but -startvirtualcamera or something similar would be a great little addition. Since I literally always use my virtual cam on my mac now, it would be a great default. Here's a reference to the flags that are currently available: https://obsproject.com/wiki/Launch-Parameters

Since I'm not a c++ dev I can't contribute any code myself, but I'll definitely be on the lookout for other ways to contribute. I'll watch the issues to see if there's anything I can help with. Thanks to all the contributors in this repo: this has changed my workflow for the better 1000%

**Comment by gxalpha** [comment] 2020-04-27 21:50
Hey, this is indeed the right place for feature requests 😃 
I like the idea! 👍 
We'll see how/if it can be implemented, I guess the OBS team has something to say about this as well.

**Comment by dodgepong** [comment] 2020-04-27 21:56
We can add that to the spec, as the feature is relatively trivial to add. That said, I don't think it can be done in a plugin alone. This is the sort of feature that might have to wait until it gets merged into OBS.

**Comment by brinsche** [comment] 2020-04-27 22:14
FWIW the OBS-VirtualCam plugin for windows has its own autostart checkbox, I think this is a feature enough people might want to warrant a setting.

**Comment by johnboiles** [comment] 2020-04-28 19:35
This is a great idea. As @dodgepong mentions we might not be able to do this until this is merged into OBS because I don't think we can get commandline arguments from the plugin (though please try to prove me wrong).

An autostart setting would be a nice to have. We could just save some state to a file and then look at that when this plugin is loaded to decide whether to start or not.

**Comment by dodgepong** [comment] 2020-04-28 19:39
> An autostart setting would be a nice to have

Note that the current version of the RFC specifies that an auto-start checkbox be added, as well as a horizontal flip option.

**Comment by johnboiles** [comment] 2020-05-12 18:59
I'm going to repurpose this issue to be about an autostart checkbox. I don't think there's a way we can autostart this from a commandline flag until this is a part of the OBS codebase.

**Comment by gxalpha** [comment] 2020-05-28 20:29
Just noticed that #132 is a duplicate of this, but I'd rather keep 132 open since it has more valuable conversation

**Closed by gxalpha** 2020-05-28 20:29 UTC
Labels: enhancement, help wanted

**Comment by jenniferhuang** [comment] 2020-07-10 07:06
I have the same feature requirement,  is it supported now?  or are there any work round with some commands to support virtual camera to be on once we restart the OBS APP?   thanks for your information in advance.

**Comment by gxalpha** [comment] 2020-07-10 08:03
This is not supported in the yet, only in the windows version of OBS, and I don't know that we even could add this from a plugin, so you'll probably have to wait for this to be integrated into OBS.
