### ISSUE TITLE
[Support]Camera Feed not displayed within Call Microsoft Teams

### ISSUE THREAD

**Issue by Atheleos** [johnboiles/obs-mac-virtualcam#172] opened 2020-06-10 23:39 UTC
_Please read the "Discussion / Support" section of the Readme first. Only open an issue if you don't get an answer on the OBS or someone tells you to. Attention: While Zoom says they re-enabled virtual cameras, only certain ones they whitelisted work. Currently, this plugin does not work with Zoom out of the box! See https://github.com/johnboiles/obs-mac-virtualcam/wiki/Compatibility#apps-dont-allow-dal-plugins for a workaround._

**Describe the issue**

The issue occurs when in a connected video call within Teams.  The feed does not appear to the distant end.  Both the preview and live mini display within Teams show the OBS feed from the Virtual Cam but nothing appears to the remote caller or callers within the group.

**To Reproduce**
1. I open OBS Studio. I insure that feed from input device is being displayed from source.
2. Click on Tools in upper menu to start virtual cam.
3. Open Teams and verify the OBS VirtualCam is working by checking in Settings/Devices and seeing the feed in preview from the selected camera.
4. Attempt call, feed is displayed during call, but the remote caller cannot see picture.

**Desktop (please complete the following information):**
 - Platform - New MacBook Pro (16-inch, 2019)
 - OS - macOS Catalina Version 10.15.5
 - Microsoft Teams Version - 1.3.00.9271 last updated 6/10/20
 - OBS Studio Version - 25.0.8 (64 Bit)
 - OBS-VirtualCam version - obs-mac-virtualcam-3ca8f62-v1.2.0.pkg

**Additional context**
It is a new setup.  It could be as simple as a security or privacy setting that I am missing.  I have been troubleshooting those to rule them out. Suggestions on what to check would help however and thanks for a wonderful product overall despite my current dilemma as having successfully used it previously.

Also currently using latest iOS plugin from OBS to use iPhone as webcam.  However this is not what appears to be causing the problem as the issue persists with using the FaceTime HD Camera as a Video Capture Input.

**Comment by nburlett** [comment] 2020-06-17 20:52
I have the same issue. 

* Platform - iMac Pro (2017)
* OS - macOS Catalina Version 10.15.5
* Microsoft Teams Version - Microsoft Teams Version 1.3.00.9271. It was last updated on 6/9/20.
* OBS Studio Version - 25.0.8 (64 Bit)
* OBS-VirtualCam version - obs-mac-virtualcam-3ca8f62-v1.2.0.pkg

When I turn the camera on in Teams, it starts displaying the camera feed to me, but does not seem to send it anywhere else. When it is not displaying the camera, The console has repeated "Queue is full, bailing out" , but then once it starts displaying I get the following (including one queue full message from before it starts displaying)

```
default	13:47:17.259136-0700	Microsoft Teams Helper	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	13:47:17.259613-0700	Microsoft Teams Helper	obs-mac-virtualcam(DAL): HardwarePlugIn_ObjectIsPropertySettable Device(33) kCMIODevicePropertyHogMode self=0x11209d768 settable=0
default	13:47:17.259713-0700	Microsoft Teams Helper	obs-mac-virtualcam(DAL): HardwarePlugIn_ObjectIsPropertySettable Device(33) kCMIODevicePropertyExcludeNonDALAccess self=0x11209d768 settable=1
default	13:47:17.259772-0700	Microsoft Teams Helper	obs-mac-virtualcam(DAL): HardwarePlugIn_ObjectIsPropertySettable Device(33) kCMIODevicePropertyExcludeNonDALAccess self=0x11209d768 settable=1
default	13:47:17.259804-0700	Microsoft Teams Helper	obs-mac-virtualcam(DAL): HardwarePlugIn_ObjectSetPropertyData Device(33) kCMIODevicePropertyExcludeNonDALAccess self=0x11209d768 data(int)=1
default	13:47:17.261219-0700	Microsoft Teams Helper	obs-mac-virtualcam(DAL): HardwarePlugIn_ObjectIsPropertySettable Device(33) kCMIODevicePropertyDeviceMaster self=0x11209d768 settable=1
default	13:47:17.261322-0700	Microsoft Teams Helper	obs-mac-virtualcam(DAL): HardwarePlugIn_ObjectIsPropertySettable Device(33) kCMIODevicePropertyDeviceMaster self=0x11209d768 settable=1
default	13:47:17.261383-0700	Microsoft Teams Helper	obs-mac-virtualcam(DAL): HardwarePlugIn_ObjectIsPropertySettable Device(33) kCMIODevicePropertyDeviceMaster self=0x11209d768 settable=1
default	13:47:17.261418-0700	Microsoft Teams Helper	obs-mac-virtualcam(DAL): HardwarePlugIn_ObjectSetPropertyData Device(33) kCMIODevicePropertyDeviceMaster self=0x11209d768 data(int)=86275
default	13:47:17.261497-0700	Microsoft Teams Helper	obs-mac-virtualcam(DAL): Stream unhandled isPropertySettableWithAddress for kCMIOStreamPropertyFormatDescription
default	13:47:17.261531-0700	Microsoft Teams Helper	obs-mac-virtualcam(DAL): HardwarePlugIn_ObjectIsPropertySettable Stream(34) kCMIOStreamPropertyFormatDescription self=0x11209d768 settable=0
error	13:47:17.261571-0700	Microsoft Teams Helper	CMIOHardware.cpp:436:CMIOObjectSetPropertyData property isn't settable pft  glob
default	13:47:17.261641-0700	Microsoft Teams Helper	obs-mac-virtualcam(DAL): Stream unhandled isPropertySettableWithAddress for kCMIOStreamPropertyFrameRate
default	13:47:17.261673-0700	Microsoft Teams Helper	obs-mac-virtualcam(DAL): HardwarePlugIn_ObjectIsPropertySettable Stream(34) kCMIOStreamPropertyFrameRate self=0x11209d768 settable=0
error	13:47:17.261704-0700	Microsoft Teams Helper	CMIOHardware.cpp:436:CMIOObjectSetPropertyData property isn't settable nfrt glob
default	13:47:17.261770-0700	Microsoft Teams Helper	obs-mac-virtualcam(DAL): Stream unhandled isPropertySettableWithAddress for kCMIOStreamPropertyMinimumFrameRate
default	13:47:17.261802-0700	Microsoft Teams Helper	obs-mac-virtualcam(DAL): HardwarePlugIn_ObjectIsPropertySettable Stream(34) kCMIOStreamPropertyMinimumFrameRate self=0x11209d768 settable=0
error	13:47:17.261832-0700	Microsoft Teams Helper	CMIOHardware.cpp:436:CMIOObjectSetPropertyData property isn't settable mfrt glob
default	13:47:17.264667-0700	Microsoft Teams Helper	CMIO_Unit_ScopeElement.h:200:SafeGetElement Throwing err: -67454, elementIndex: 1
default	13:47:17.265377-0700	Microsoft Teams Helper	obs-mac-virtualcam(DAL): Device unhandled hasPropertyWithAddress for kCMIODevicePropertyLinkedAndSyncedCoreAudioDeviceUID
default	13:47:17.265427-0700	Microsoft Teams Helper	CMIOHardware.cpp:357:CMIOObjectGetPropertyData no object property for given ID 33
default	13:47:17.265459-0700	Microsoft Teams Helper	obs-mac-virtualcam(DAL): HardwarePlugIn_ObjectSetPropertyData Device(33) kCMIOObjectPropertyListenerAdded self=0x11209d768 data(int)=1818850926
default	13:47:17.265501-0700	Microsoft Teams Helper	obs-mac-virtualcam(DAL): Device unhandled setPropertyDataWithAddress for kCMIOObjectPropertyListenerAdded
default	13:47:17.266751-0700	Microsoft Teams Helper	CMIO_Unit_Input_Device.cpp:246:GetPropertyInfo CMIOUInputFromProcs::GetPropertyInfo() failed for id 102, Error: -67456
default	13:47:17.266982-0700	Microsoft Teams Helper	obs-mac-virtualcam(DAL): HardwarePlugIn_StreamCopyBufferQueue <Stream: 0x7fa6777a2580> (id=34) self=0x11209d768 queue=<CMSimpleQueue 0x7fa67753d250 retainCount: 2 allocator: 0x7fff8849cb60
	capacity = 30
	count = 30
	readIndex = 21
	writeIndex = 20
	elements[readIndex..(writeIndex-1) %% (capacity+1)] = {
		0x7fa68006dbb0,
		0x7fa680189db0,
		0x7fa677718460,
		0x7fa697461f80,
		0x7fa697461420,
		0x7fa5b05047f0,
		0x7fa6974654b0,
		0x7fa69746c9e0,
		0x7fa697578290,
		0x7fa5b02538f0,
		0x7fa6775fa7f0,
		0x7fa68059f4b0,
		0x7fa6774476d0,
		0x7fa6976d5c10,
		0x7fa6976d0630,
		0x7fa6976b9200,
		0x7fa6976cffe0,
		0x7fa5b1805b40,
		0x7fa5b0511520,
		0x7fa6976e5410,
		0x7fa6976faee0,
		0x7fa6802e7400,
		0x7fa677542990,
		0x7fa5b0262750,
		0x7fa5b024ecc0,
		0x7fa6976b1200,
		0x7fa6976dc190,
		0x7fa6775ffe00,
		0x7fa5b0253e60,
		0x7fa67771ef40}
>
default	13:47:17.267095-0700	Microsoft Teams Helper	obs-mac-virtualcam(DAL): HardwarePlugIn_DeviceStartStream self=0x11209d768 device=33 stream=34
default	13:47:17.267126-0700	Microsoft Teams Helper	obs-mac-virtualcam(DAL): -[PlugIn startStream]
default	13:47:17.267182-0700	Microsoft Teams Helper	obs-mac-virtualcam(DAL): -[Stream startServingDefaultFrames]
default	13:47:17.267230-0700	Microsoft Teams Helper	obs-mac-virtualcam(DAL): HardwarePlugIn_ObjectIsPropertySettable Device(33) kCMIODevicePropertyDeviceMaster self=0x11209d768 settable=1
default	13:47:17.267311-0700	Microsoft Teams Helper	obs-mac-virtualcam(DAL): HardwarePlugIn_ObjectIsPropertySettable Device(33) kCMIODevicePropertyDeviceMaster self=0x11209d768 settable=1
default	13:47:17.267362-0700	Microsoft Teams Helper	obs-mac-virtualcam(DAL): HardwarePlugIn_ObjectIsPropertySettable Device(33) kCMIODevicePropertyDeviceMaster self=0x11209d768 settable=1
default	13:47:17.267433-0700	Microsoft Teams Helper	obs-mac-virtualcam(DAL): HardwarePlugIn_ObjectSetPropertyData Device(33) kCMIODevicePropertyDeviceMaster self=0x11209d768 data(int)=-1
default	13:47:17.268243-0700	Microsoft Teams Helper	obs-mac-virtualcam(DAL): Attempting connection
default	13:47:17.268286-0700	Microsoft Teams Helper	obs-mac-virtualcam(DAL): -[MachClient connectToServer]
default	13:47:17.294846-0700	Microsoft Teams Helper	obs-mac-virtualcam(DAL): -[Stream stopServingDefaultFrames]
default	13:47:21.887806-0700	runningboardd	Invalidating assertion 294-141-18722 (target:executable<Teams(4420)>) from originator 141
default	13:47:21.996825-0700	runningboardd	[executable<Teams(4420)>:86213] Ignoring jetsam update because this process is not memory-managed
default	13:47:21.997010-0700	runningboardd	[executable<Teams(4420)>:86213] Set darwin role to: UserInteractiveNonFocal
default	13:47:21.997116-0700	runningboardd	[executable<Teams(4420)>:86213] Ignoring GPU update because this process is not GPU managed
```

The OBS virtual camera works correctly when running the Teams webpage from within Chrome.

**Comment by FRoXXF05** [comment] 2020-06-28 08:36
Having exactly the same issue. I would love to see a fix.

**Comment by arkany** [comment] 2020-06-29 04:56
I'm having similar issues, but I can't even get the camera to appear in Teams. I still want to follow along on this bug.

**Comment by jianhuayang** [comment] 2020-06-30 13:06
The same here. In Teams, it displays flipped video, and it shows only on my side i.e. not the remote side. I also tried to record a meeting (only with myself), but no video is captured at all. 

Tried QuickTime, seems the virtual camera works properly. Tried reinstall OBS & Teams, didn't work.

**Comment by gxalpha** [comment] 2020-06-30 13:15
The video isn't flipped, this is just your preview.

**Comment by davidsak** [comment] 2020-07-24 15:33
Found what might be a work around. Install Snap Camera, select OBS Virtual Camera as your video source in Snap Camera, in Teams, select Snap Camera instead of OBS. You'll also now be able to apply AR filters atop the OBS layer.

**Comment by nburlett** [comment] 2020-07-26 01:19
@davidsak , I tried Snap Camera, and I have basically the same problem with Snap Camera as with OBS VirtualCam. Teams running in Chrome will broadcast the video to the other participants for both Snap and OBS VirtualCam. Teams running as a native mac application will show me the preview of the Snap or OBS VirtualCam, but will not broadcast the video to the other participants.

**Comment by x-stefan** [comment] 2020-07-30 08:41
So far I know this issue is caused by Apples [Library Validation](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_cs_disable-library-validation).

This restriction blocks any plugins that aren’t digitally signed and MS Teams seems to have implemented that with an update ~2 weeks ago.

https://techcommunity.microsoft.com/t5/microsoft-teams/7-17-2020-latest-teams-update-breaks-virtual-cameras-microsoft/m-p/1527271

**Comment by gxalpha** [comment] 2020-07-30 08:48
Yes, as described multiple times nearly everywhere on this GitHub. See [the wiki](https://github.com/johnboiles/obs-mac-virtualcam/wiki/Compatibility#apps-dont-allow-dal-plugins) for further information.

**Comment by bumbleparrot** [comment] 2020-08-03 17:22
To help people, you have to do this to "unsign" the app that can't see the virtual camera.

sudo codesign --remove-signature "/Applications/Microsoft Teams.app"
sudo codesign --remove-signature "/Applications/Microsoft Teams.app/Contents/Frameworks/Microsoft Teams Helper.app"

**Comment by pdemro** [comment] 2020-08-04 15:25
If you get here, please vote this issue up on the official Microsoft user voice:  https://microsoftteams.uservoice.com/forums/908686-bug-reports/suggestions/40961347-latest-teams-update-breaks-virtual-cameras-micro

**Comment by nburlett** [comment] 2020-08-05 21:45
> To help people, you have to do this to "unsign" the app that can't see the virtual camera.
> 
> sudo codesign --remove-signature "/Applications/Microsoft Teams.app"
> sudo codesign --remove-signature "/Applications/Microsoft Teams.app/Contents/Frameworks/Microsoft Teams Helper.app"

These instructions solve issue #171, but not this issue. 

In this issue, the problem is that after the binary has been unsigned, and the OBS Virtual Camera is selected in Teams, it shows the camera image locally but *does not* transmit the image to the remote participants.

**Comment by gxalpha** [comment] 2020-08-06 11:14
@nburlett could you please explain? You mean that in your preview the camera works but other participants can't see it? That sounds like a Teams issue to me

**Comment by nburlett** [comment] 2020-08-06 16:44
@gxalpha ,

The problem I'm having is described by @Atheleos in the original post on this issue, and again the [post I made June 17](#issuecomment-645618408). The OBS Virtual Cam shows up in Teams and can be selected as the camera. I see the preview image as if it's being transmitted to the other participants, but they see only my user icon (as if I wasn't transmitting). If I switch to my built-in camera, it both displays the preview and transmits so the other participants can see. Switching back to OBS shows me the OBS camera preview, but the other participants a frozen version of the previous camera. (my iMac is rotated 90° on a VESA mount and thus my built-in camera transmits a rotated image... hence the need for a virtual camera).

It might be a Teams issue, but the problem is limited to virtual cameras. I recently got an elgato Cam Link 4K, and it works correctly in Teams.

So far I've tried Teams on three machines, all running Catalina 10.15.6: 
- MacBook Pro (16-inch, 2019) **issue reproduces**
- iMac Pro (2017) **issue reproduces**
- MacBook Pro (Retina, 15-inch, Mid 2015) **obs virtual cam works**

**Comment by amdjml** [comment] 2020-08-27 17:52
Virtual camera used to work on MS Teams, but after a recent update, it has stopped working. It no longer shows up under Settings > Devices > Camera. I am running the latest version of "obs-mac-virtualcam" and Microsoft Teams Version is 1.3.00.18164.

Was wondering if anyone has the same issue and if you know of any workaround?

**Comment by nburlett** [comment] 2020-08-27 19:59
@amdjml , the issue you're describing tracked in #171, and is tracked by Microsoft at https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-on-mac/virtual-camera-doesnt-work-macos .  There are workarounds in #171 which you might try.

The issue here is that even with the workarounds, some machines will display the camera feed preview locally, but will not transmit the video to the other participants.

**Comment by LonnekeACB** [comment] 2020-11-10 21:09
Anyone managed to solve this, or found a workaround?
This is the only place on the web where I even found this problem mentioned. 
It seems specific for the combination OBS virtual cam - MS Teams/Skype. Because I just discovered that I do can use a virtual cam on Skype, but when choosing OBS VC the other participants see my user icon, just as nburlett explained about MS Teams, in which I have the same experience..

**Comment by marsrobertson** [comment] 2020-11-12 21:18
OBS not even running.

Google brought me here.

> Device unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects

![image](https://user-images.githubusercontent.com/44369284/98997441-68aeb180-252c-11eb-8001-f82fbbc151b5.png)

**Comment by Zielgestalt** [comment] 2020-11-13 12:35
I had the same problem. Teams with my OBS Virtual Camera showing in my own preview, but nothing to other participants. Then I switched my Teams Cam to another virtual camera by CamTwist. That worked. And then back to OBS Virtual Cam. And now this cam is working, too.

Sorry - I don't know why this works and I know this is not a reliable workaround. And after a reboot I have to do that again. But it's better than nothing...

**Comment by edouard-gv** [comment] 2020-11-20 08:52
I have the same issue on Windows 10 (obs virtual cam visible in my own preview, but not in other participant's, with Teams).

**Comment by gxalpha** [comment] 2020-11-20 09:42
@edouard-gv this is only for the Mac version, for support on the windows one please go to the obs discord

**Comment by edouard-gv** [comment] 2020-11-20 11:08
(I was just trying to help saying that it might not specific to the mac version...)

**Comment by gxalpha** [comment] 2020-11-20 14:12
i see
Thing is that the windows and mac versions have pretty much nothing in common.
But thanks for trying to help!

**Comment by stezz** [comment] 2020-11-23 08:13
Only workaround I could find is to pass the OBS Virtual Camera stream to CamTwist and use that inside Teams.

You can do that by opening CamTwist and selecting "Webcam" from Video Sources and OBS Virtual Camera as Camera.

So this becomes: Your Camera -> OBS -> OBS Virtual Camera -> CamTwist -> Teams 

(A bit of a long chain... )

Tested with Microsoft Teams Version 1.3.00.28778, OBS 26.0.2, Camtwist 3.4.3

**Comment by johnboiles** [comment] 2020-12-14 23:36
Closing as a dupe of #4 but it would be great to compile all the per-app workarounds into the OBS wiki somewhere.

**Closed by johnboiles** 2020-12-14 23:36 UTC
