### ISSUE TITLE
Virtual cam not working with Mojave 10.14.6

### ISSUE THREAD

**Issue by cesarhernandezgt** [johnboiles/obs-mac-virtualcam#88] opened 2020-05-12 22:41 UTC
System:
OS version: 10.14.6 
OBS version: 25.0.8
Virtualcam version: Official release: obs-mac-virtualcam-5db91b4-v1.0.0.pkg

- I installed the 25.0.8 version of OBS, installed the plugin.
- OBS start and after clicking on `Start Virtual Camera`, nothing appears on any video app (tested QuickTime Player, facetime, Skype). 

![image](https://user-images.githubusercontent.com/1454523/81752536-dd663d80-946e-11ea-95ef-89dc127ee0f2.png)

Yes, I restarted even the laptop after installation.

OBS Logs: 
```
16:39:10.522: CPU Name: Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
16:39:10.522: CPU Speed: 3500MHz
16:39:10.522: Physical Cores: 2, Logical Cores: 4
16:39:10.522: Physical Memory: 16384MB Total
16:39:10.522: OS Name: Mac OS X (NSMACHOperatingSystem)
16:39:10.522: OS Version: Version 10.14.6 (Build 18G4032)
16:39:10.522: Kernel Version: 18.7.0
16:39:10.530: hotkeys-cocoa: Using layout 'com.apple.keylayout.US'
16:39:10.531: Portable mode: false
16:39:10.742: OBS 25.0.8 (mac)
16:39:10.742: ---------------------------------
16:39:10.743: ---------------------------------
16:39:10.743: audio settings reset:
16:39:10.743: 	samples per sec: 44100
16:39:10.743: 	speakers:        2
16:39:10.744: ---------------------------------
16:39:10.744: Initializing OpenGL...
16:39:10.770: Loading up OpenGL on adapter Intel Inc. Intel(R) Iris(TM) Plus Graphics 650
16:39:10.771: OpenGL loaded successfully, version 4.1 INTEL-12.10.17, shading language 4.10
16:39:10.866: ---------------------------------
16:39:10.866: video settings reset:
16:39:10.866: 	base resolution:   1280x720
16:39:10.866: 	output resolution: 1280x720
16:39:10.866: 	downscale filter:  Bicubic
16:39:10.866: 	fps:               60/1
16:39:10.866: 	format:            NV12
16:39:10.866: 	YUV mode:          601/Partial
16:39:10.866: NV12 texture support not available
16:39:10.866: Audio monitoring device:
16:39:10.866: 	name: Default
16:39:10.866: 	id: default
16:39:10.866: ---------------------------------
16:39:10.870: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
16:39:10.876: os_dlopen(libpython3.7m.dylib->libpython3.7m.dylib): dlopen(libpython3.7m.dylib, 257): image not found
16:39:10.876: 
16:39:10.876: [Python] Could not load library: libpython3.7m.dylib
16:39:10.937: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
16:39:10.937: No blackmagic support
16:39:11.026: [VideoToolbox encoder]: Adding VideoToolbox H264 encoders
16:39:11.050: [obs-browser]: Version 2.8.6
16:39:11.065: VLC found, VLC video source enabled
16:39:11.066: os_dlopen(/Library/Application Support/obs-studio/plugins/StreamDeckPlugin/bin/StreamDeckPlugin.so->/Library/Application Support/obs-studio/plugins/StreamDeckPlugin/bin/StreamDeckPlugin.so): dlopen(/Library/Application Support/obs-studio/plugins/StreamDeckPlugin/bin/StreamDeckPlugin.so, 257): Library not loaded: @rpath/../bin/libobs.0.dylib
16:39:11.066:   Referenced from: /Library/Application Support/obs-studio/plugins/StreamDeckPlugin/bin/StreamDeckPlugin.so
16:39:11.066:   Reason: image not found
16:39:11.066: 
16:39:11.066: Module '/Library/Application Support/obs-studio/plugins/StreamDeckPlugin/bin/StreamDeckPlugin.so' not loaded
16:39:11.066: Ignoring old obs-browser.so version
16:39:11.069: Failed to load 'en-US' text for module: 'obs-mac-virtualcam.so'
16:39:11.070: os_dlopen(/Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so->/Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so): dlopen(/Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so, 257): Library not loaded: @rpath/QtWidgets
16:39:11.070:   Referenced from: /Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so
16:39:11.070:   Reason: image not found
16:39:11.070: 
16:39:11.070: Module '/Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so' not loaded
16:39:11.070: ---------------------------------
16:39:11.070:   Loaded Modules:
16:39:11.070:     obs-mac-virtualcam.so
16:39:11.070:     vlc-video.so
16:39:11.070:     text-freetype2.so
16:39:11.070:     rtmp-services.so
16:39:11.070:     obs-x264.so
16:39:11.070:     obs-vst.so
16:39:11.070:     obs-transitions.so
16:39:11.070:     obs-outputs.so
16:39:11.070:     obs-libfdk.so
16:39:11.070:     obs-filters.so
16:39:11.070:     obs-ffmpeg.so
16:39:11.070:     obs-browser.so
16:39:11.070:     mac-vth264.so
16:39:11.070:     mac-syphon.so
16:39:11.070:     mac-decklink.so
16:39:11.070:     mac-capture.so
16:39:11.070:     mac-avcapture.so
16:39:11.070:     linux-jack.so
16:39:11.070:     image-source.so
16:39:11.071:     frontend-tools.so
16:39:11.071:     decklink-ouput-ui.so
16:39:11.071:     coreaudio-encoder.so
16:39:11.071: ---------------------------------
16:39:11.071: os_dlopen(../obs-plugins/obs-browser->../obs-plugins/obs-browser.so): dlopen(../obs-plugins/obs-browser.so, 257): image not found
16:39:11.071: 
16:39:11.071: ==== Startup complete ===============================================
16:39:11.071: obs-data.c: [obs_data_create_from_json] Failed reading json string (-1): wrong arguments
16:39:11.086: All scene data cleared
16:39:11.086: ------------------------------------------------
16:39:11.169: coreaudio: device 'Soundflower (2ch)' initialized
16:39:11.169: [Loaded global audio device]: 'Desktop Audio'
16:39:11.641: coreaudio: device 'Soundflower (2ch)' initialized
16:39:11.641: [Loaded global audio device]: 'Desktop Audio 2'
16:39:11.644: coreaudio: device 'AG06/AG03' initialized
16:39:11.644: [Loaded global audio device]: 'Mic/Aux'
16:39:11.644:     - filter: 'Compressor' (compressor_filter)
16:39:11.694: adding 46 milliseconds of audio buffering, total audio buffering is now 46 milliseconds (source: Desktop Audio 2)
16:39:11.694: 
16:39:11.865: [Media Source 'IntroVideo']: settings:
16:39:11.865: 	input:                   /Users/cesar/Downloads/White Product Marketing  Animated and Video Presentation.mp4
16:39:11.865: 	input_format:            (null)
16:39:11.865: 	speed:                   100
16:39:11.865: 	is_looping:              yes
16:39:11.865: 	is_hw_decoding:          no
16:39:11.865: 	is_clear_on_media_end:   no
16:39:11.865: 	restart_on_activate:     yes
16:39:11.865: 	close_when_inactive:     no
16:39:11.881: Canon 4k: Selected device 'Cam Link 4K'
16:39:11.884: Canon 4k: Using preset 1280x720
16:39:11.957: Video Capture Device: No device selected
16:39:11.958: Switched to scene 'Scene'
16:39:11.958: ------------------------------------------------
16:39:11.958: Loaded scenes:
16:39:11.958: - scene 'Scene':
16:39:11.958:     - source: 'Canon 4k' (av_capture_input)
16:39:11.958:     - source: 'Video Capture Device' (av_capture_input)
16:39:11.958: - scene 'Intro':
16:39:11.958:     - source: 'IntroVideo' (ffmpeg_source)
16:39:11.958:     - source: 'IntroImage' (image_source)
16:39:11.958:     - source: 'TEXT - Countdown Timer' (text_ft2_source)
16:39:11.958: ------------------------------------------------
16:39:12.033: Switched to Preview/Program mode
16:39:12.033: ------------------------------------------------
16:39:32.819: Switched to scene 'Scene'
16:39:32.822: Switched to regular Preview mode
16:39:32.822: ------------------------------------------------
16:39:34.342: Switched to Preview/Program mode
16:39:34.344: ------------------------------------------------
16:39:35.400: User switched to scene 'Intro'
16:39:37.538: User switched to scene 'Scene'

```

**Comment by johnboiles** [comment] 2020-05-12 22:47
Duplicate of #85.

**Closed by johnboiles** 2020-05-12 22:47 UTC

**Comment by johnboiles** [comment] 2020-05-12 22:48
But thank you for the thorough report! I definitely could use some help from someone with an older version of macOS to try to figure out how to modify the build to support older versions of macOS as well.
