### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by therealdanbient** [johnboiles/obs-mac-virtualcam#142] opened 2020-05-26 01:13 UTC
**Describe the bug**
OBS video feed into Zoom is angled/not straight

**To Reproduce**
1. Open OBS
2. Start Virtual Cam
3. Start Zoom
4. Choose OBS Virtual Cam

**Expected behavior**
Direct transmission of Image in OBS into Zoom

**Screenshots**
![overlay of image in Zoom](https://user-images.githubusercontent.com/63126965/82850995-5bddc900-9ecc-11ea-8570-2ba989111d4d.png)
![Screen Shot 2020-05-25 at 9 09 01 PM](https://user-images.githubusercontent.com/63126965/82851051-8596f000-9ecc-11ea-88ad-182ec843e4bd.png)

**Desktop (please complete the following information):**
 - OS version: MacOS High Sierra
 - Application: Zoom
 - Virtualcam version: 1.1.0]
 - OBS version: 25.0.8
**Additional context**

**Comment by Resseguie** [comment] 2020-05-26 19:50
Duplicate of #135 ?

**Comment by gxalpha** [comment] 2020-05-26 19:56
yes. You're right.

**Closed by gxalpha** 2020-05-26 19:56 UTC
