### ISSUE TITLE
[BUG] Virtual camera output full blurred, fuzzy

### ISSUE THREAD

**Issue by anthonypillot** [johnboiles/obs-mac-virtualcam#238] opened 2020-11-23 16:25 UTC
**Describe the bug**
Installed the plugin, the plugin worked fine on Google Chrome, Google Meet : I was able to seen my OBS diffusion on Google Meet.

But after a restart of Chrome, the stream is full blurred, stripped. (I don't know how clearly describe my problem so, just look at the screenshot in Google Meet.)

**To Reproduce**
Trying to reproduce the bug, reinstalling the plugin, restart my computer, full reinstall OBS, the plugin, but nothing works again.

**Expected behavior**
Just see my diffusion in Google Meet.

**Screenshots**

<img width="1383" alt="Capture d’écran 2020-11-23 à 17 21 17" src="https://user-images.githubusercontent.com/51130139/99987443-c48cfc00-2db0-11eb-8353-fbd5fcc4e871.png">

**Desktop (please complete the following information):**
 - OS version: [macOS Big Sur 11.0.1]
 - Application: [Chrome, Google Meet]
 - Virtualcam version: [1.2.1]
 - OBS version: [26.0.2]

**Comment by PatMat-71** [comment] 2020-11-24 18:04
Hi,
i have the same problem, with the same Setup, but the Application is MS Teams on Chrome.
![image](https://user-images.githubusercontent.com/74983817/100134058-ec02c800-2e87-11eb-8df9-d2aeb13db238.png)

**Comment by medwingADMIN** [comment] 2020-11-25 11:02
Same thing on my end

**Comment by rjmunro** [comment] 2020-11-25 11:31
The word you want is not blurred or fuzzy, it's "skewed". See https://github.com/johnboiles/obs-mac-virtualcam/issues/160.

**Comment by johnboiles** [comment] 2020-11-26 23:42
Yeah dupe of #160. Can y’all post your deets there? Also include the model of the Mac you have. Seems like this is more prevalent on older macs

**Closed by johnboiles** 2020-11-26 23:42 UTC
