### ISSUE TITLE
[Support] Cannot get virtual camera to show up in Teams on MacOS Catalina

### ISSUE THREAD

**Issue by andrasg** [johnboiles/obs-mac-virtualcam#171] opened 2020-06-10 21:06 UTC
**Describe the issue**
Installed virtual camera, started it in OBS, quit and relaunched Teams. Camera is not showing up as an available input in Teams. Virtual camera works in other apps (eg: jitsi meet in Edge browser)

**To Reproduce**
1. install latest OBS
2. install latest virtual camera release
3. start OBS
4. start virtual camera
5. quit and restart Teams
6. try to select virtual camera in Teams > settings > Devices
 
**Behavior**
Virtual Camera is not appearing as a selectable input in Microsoft Teams. Works in other apps.

**Desktop (please complete the following information):**
 - OS version: macOS Catalina 10.15.6 Beta (19G36e)
 - Application (if applicable): Microsoft Teams 1.3.00.15365
 - Virtualcam version: 1.2.0
 - OBS version: 25.0.8 64 bit

**Comment by davenelsen** [comment] 2020-06-14 12:10
I had a similar issue with Zoom and found a resolution. Maybe this will work for you too. When I installed the latest versions of OBS and John's virtualcam on a new Mac Mini running Catalina (John - thank you, thank you, thank you for creating this product), I had no problems using the virtualcam with Zoom (after un-signing Zoom that is). However, when I installed the same exact software on my Macbook Pro (upgrading from an earlier unofficial version of John's software), the virtualcam did not show up as an option in Zoom. Eventually, I noticed that the file /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin had different dates on the two machines. Apparently, it was not updated when I did the update. I deleted it (only that file, nothing else) and then reinstalled John's official virtualcam release and voila, the camera now appears in Zoom.

FWIW, this is how I discovered that this file might be the issue:

system_profiler SPCameraDataType 2020-06-13 08:12:32.220 system_profiler[1404:29681] Error loading /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam:  dlopen(/Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam, 0x0106): code signature in (/Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam) not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)      

FaceTime HD Camera (Built-in):        Model ID: UVC Camera VendorID_1452 ProductID_34068       Unique ID: 0x8020000005ac8514

**Comment by mrjoshuap** [comment] 2020-06-17 20:06
I had a similar problem to @davenelsen and can confirm that performing "uninstall" directions and the doing a clean install fixed this issue for me as well.  Note that for me, it was not limited to Teams, but all similar softwares.

**Comment by DominicTremblay314** [comment] 2020-07-07 19:01
I also have this problem. Virtual camera will not show in Teams, but will show in Google Meet.

MacBook Pro 15" (2019)
Mac OS Mojave 10.14.6
OBS 25.0.8 64 bits
Mac Virtual Cam v1.2.0

Error message in console:

Library Validation failed: Rejecting '/Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam' (Team ID: 62G85M9ZN5, platform: no) for process 'Teams(43797)' (Team ID: UBF8T346G9, platform: no), reason: mapping process and mapped file (non-platform) have different Team IDs

**Comment by gxalpha** [comment] 2020-07-07 19:11
Yeah it looks like you guys need to resign the app to get it working, the the Compatibility page in the wiki for further details

**Comment by Sabre170** [comment] 2020-07-17 18:41
I was having the same issue.  Zoom and Teams would not recognize the virtual cam running.  I solved this issue by following the plugin uninstall instructions [Here](https://github.com/johnboiles/obs-mac-virtualcam/wiki/Installing) and then reinstalling with the install instructions on the same page.  Now everything is good to go.

**Comment by bumbleparrot** [comment] 2020-08-03 17:22
To help people, you have to do this to "unsign" the app that can't see the virtual camera.

sudo codesign --remove-signature "/Applications/Microsoft Teams.app"
sudo codesign --remove-signature "/Applications/Microsoft Teams.app/Contents/Frameworks/Microsoft Teams Helper.app"

**Comment by salavatkhafizov** [comment] 2020-10-10 20:29
@bumbleparrot  Thanks! It worked now with MS Teams)) 
Macbook Pro Retina 2012
Latest OS Catalina, Virtual Cam  plugin, OBS 
FaceTime camera on Macbook

**Comment by stuffimade** [comment] 2020-10-21 06:30
For the latest update to TEAMS.... just un-signing it didn't work for me.
I uninstalled, re-installed, allowed it access to my KeyChain, then quite the app.
I then opened terminal and ran;
sudo codesign --remove-signature "/Applications/Microsoft Teams.app"
sudo codesign --remove-signature "/Applications/Microsoft Teams.app/Contents/Frameworks/Microsoft Teams Helper.app"

ta g

**Comment by jmaslibre-pp** [comment] 2020-10-28 00:15
https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-on-mac/virtual-camera-doesnt-work-macos

**Comment by rafaeldcf** [comment] 2020-11-10 14:50
I fixed the issue following these steps:
xcode-select --install
(if you see an error, use the following link https://developer.apple.com/download/more/?=command%20line%20tools)

Follow the steps described in this link (there is an update in the post):
https://answers.microsoft.com/en-us/msteams/forum/msteams_tfb-msteams_tfmac/microsoft-teams-mac-os-client-is-not-recognizing/d9e863be-d9a4-4d03-a4b8-1b5c7df58828

It worked for me in MacOS Catalina & Microsoft Teams.

**Comment by karm435** [comment] 2020-11-12 22:56
This worked for me one the latest releasee 
https://answers.microsoft.com/en-us/msteams/forum/msteams_tfb-msteams_tfmac/microsoft-teams-mac-os-client-is-not-recognizing/d9e863be-d9a4-4d03-a4b8-1b5c7df58828

**Comment by ClickSimply** [comment] 2020-11-16 18:50
To save everyone time, the link above says the new working commands are:
```
sudo codesign --remove-signature "/Applications/Microsoft Teams.app"
sudo codesign --remove-signature "/Applications/Microsoft Teams.app/Contents/Frameworks/Microsoft Teams Helper.app"
sudo codesign --remove-signature "/Applications/Microsoft Teams.app/Contents/Frameworks/Microsoft Teams Helper (GPU).app"
sudo codesign --remove-signature "/Applications/Microsoft Teams.app/Contents/Frameworks/Microsoft Teams Helper (Plugin).app"
sudo codesign --remove-signature "/Applications/Microsoft Teams.app/Contents/Frameworks/Microsoft Teams Helper (Renderer).app"
```

Worked for me in macOS Big Sur when the previous commands didn't.

**Comment by TypedLambda** [comment] 2020-11-19 14:31
For me removing the renderer signature was to enough I left the other signatures intact.
```
sudo codesign --remove-signature "/Applications/Microsoft Teams.app/Contents/Frameworks/Microsoft Teams Helper (Renderer).app"
```
I could ad-hoc sign it again it with the default key
```
sudo codesign -s - "/Applications/Microsoft Teams.app/Contents/Frameworks/Microsoft Teams Helper (Renderer).app"
```
so it is signed again, just with the adhoc key.

**Comment by ogermer** [comment] 2020-11-25 20:11
Removing the signature on the Renderer worked for me.

**Comment by johnboiles** [comment] 2020-12-14 23:35
Duplicate of #4 but it would be really great to start compiling these per-app workarounds into a centralized place.

**Closed by johnboiles** 2020-12-14 23:35 UTC
