### ISSUE TITLE
[BUG] BlueJeans Events does not find OBS-Camera

### ISSUE THREAD

**Issue by ssbarnea** [johnboiles/obs-mac-virtualcam#226] opened 2020-10-12 14:26 UTC
**Describe the bug**
BlueJean Events fails to detect OBS Camera and BlueJeans for Mac does instantly logs out the user when trying to change source camera.

**To Reproduce**
Download BlueJeans and BlueJeans Events from https://www.bluejeans.com/downloads 

**Expected behavior**
Be able to use OBS Camera as source with both BlueJeans Apps.

**Desktop (please complete the following information):**
 - OS version: [e.g. macOS Catalina 10.15.7]
 - Application: BlueJeans and BlueJeans Events
 - Virtualcam version: 26.0.2
 - OBS version: [e.g. 25.0.8]

**Additional context**
Other apps like Zoom or Google Chat seems to work fine with OBS virtual camera.

**Comment by gxalpha** [comment] 2020-10-13 13:38
Could you add logs from Console.app with `obs-mac-virtualcam`?

**Comment by ssbarnea** [comment] 2020-10-13 15:52
I am happy to help but there are few issues:
* BlueJeans standard edition logs me out, so I Console.app is closed too.
* BlueJeans Events starts video only if you join an event where you are a presenter, something I had to do for the first time yesterday. I am unable to initiate an event myself (i will try to get someone's to do it for me).
* Which logs from Console.app should I export? Or which app name should I filter upon?

Do these help?
https://sbarnea.com/ss/BlueJeans.2020-10-12_13-44.log
https://sbarnea.com/ss/blueMedia.2020-10-12_13-45-32.48.log

**Comment by gxalpha** [comment] 2020-10-13 20:10
Unfortunately I don't know what the BlueJeans logs are telling me :(
In Console.app, filter for `obs-mac-virtualcam`

**Comment by johnboiles** [comment] 2020-12-14 23:33
Likely a duplicate of #4.

**Closed by johnboiles** 2020-12-14 23:33 UTC
