### ISSUE TITLE
Scrambled output to Google Meet, but fine in Zoom

### ISSUE THREAD

**Issue by glennc007** [johnboiles/obs-mac-virtualcam#201] opened 2020-08-25 11:44 UTC
While I am able to select OBS Virtualcam in Google Meet, the image appears as a scramble.  In Zoom, it works fine. 
Meet 
![Screen Shot 2020-08-25 at 7 17 37 AM](https://user-images.githubusercontent.com/70206573/91170216-88110d80-e6a6-11ea-9850-312af39445c5.png)

Zoom
![Screen Shot 2020-08-25 at 7 44 15 AM](https://user-images.githubusercontent.com/70206573/91170380-cdcdd600-e6a6-11ea-94b4-2e15b4edcaa0.png)

I tried removing and reinstalling OBS virtual cam, but no change.  Tried restarting, quitting and restarting chrome, etc etc. and no change.

 - OS version: MacOS High Sierra
 - Application: Chrome / Google Meet
 - Virtualcam version: 1.2.0
 - OBS version:  25.0.8

**Comment by gxalpha** [comment] 2020-08-25 15:33
Duplicate of #160 
This is a bug we don't really know how to fix (at least no one has succeeded). 
First (if you haven't already) set both the canvas as well as the output resolution to 1280*720.
If that doesn't help, it seems that completely removing the plugin sometimes can, otherwise there are some janky workarounds at #160. Also please refer there for further conversation :)

**Closed by gxalpha** 2020-08-25 15:33 UTC
Labels: bug, duplicate

**Comment by glennc007** [comment] 2020-08-25 20:04
Thank you.   I had searched but somehow missed that post.   Setting both to
the same resolution of 1280x720 and then restarting macOS fixes the issue.
We’ll see if it holds.
